In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [22]:
# Read previously cleaned file
df=pd.read_csv('MovieDataCleanedDataSet.csv')
df.head()

,id,title,imdb_id,overview,genres,tagline,production_companies,cast,director,tags
0,27205,Inception,tt1375666,"Cobb, a skilled thief who commits corporate es...","Action, Thriller, Science Fiction, Mystery, Ad...",Your mind is the scene of the crime.,"Legendary Pictures, Warner Bros., Syncopy","Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",Christopher Nolan,"Cobb, a skilled thief who commits corporate es..."
1,155,The Dark Knight,tt0468569,Batman raises the stakes in his war on crime. ...,"Drama, Action, Crime, Thriller",Why So Serious?,"DC Comics, Legendary Pictures, Warner Bros., D...","Christian Bale, Michael Caine, Heath Ledger, A...",Christopher Nolan,Batman raises the stakes in his war on crime. ...
2,19995,Avatar,tt0499549,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction",Enter the World of Pandora.,"Ingenious Film Partners, Twentieth Century Fox...","Sam Worthington, Zoe Saldana, Sigourney Weaver...",James Cameron,"In the 22nd century, a paraplegic Marine is di..."
3,24428,The Avengers,tt0848228,When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure",Some assembly required.,"Paramount Pictures, Marvel Studios","Robert Downey Jr., Chris Evans, Mark Ruffalo, ...",Joss Whedon,When an unexpected enemy emerges and threatens...
4,293660,Deadpool,tt1431045,Deadpool tells the origin story of former Spec...,"Action, Adventure, Comedy",Witness the beginning of a happy ending,"Twentieth Century Fox Film Corporation, Marvel...","Ryan Reynolds, Morena Baccarin, Ed Skrein, T.J...",Tim Miller,Deadpool tells the origin story of former Spec...

In [23]:
# Check for nulls
df.isnull().sum()

id                        0
title                     0
imdb_id                   0
overview                  6
genres                    1
tagline                 590
production_companies     22
cast                      6
director                  0
tags                      0
dtype: int64

### Basic EDA (Reviewing Null Columns

In [24]:
# Some records existing with null values in overview, genres, tagline and production companies. This is fine as long as tags column isn't empty

In [25]:
df[df['overview'].isna()]

,id,title,imdb_id,overview,genres,tagline,production_companies,cast,director,tags
3047,35554,Cado dalle nubi,tt1526741,NaN,Comedy,NaN,"Apulia Film Commission, Taodue Film","Checco Zalone, Giulia Michelini, Dino Abbresci...",Gennaro Nunziante,"Comedy Checco Zalone, Giulia Michelini, Dino ..."
3246,50531,Chiedimi se sono felice,tt0252985,NaN,"Comedy, Drama",NaN,NaN,"Aldo Baglio, Giovanni Storti, Giacomo Poretti,...",Massimo Venier,"Comedy, Drama Aldo Baglio, Giovanni Storti, G..."
4172,58013,The Santa Claus Gang,tt1680095,NaN,Comedy,NaN,"Medusa Film, Agidi","Aldo Baglio, Giovanni Storti, Giacomo Poretti,...",Paolo Genovese,"Comedy Aldo Baglio, Giovanni Storti, Giacomo ..."
4195,57112,Tu la conosci Claudia?,tt0418259,NaN,Comedy,NaN,"Medusa Film, Agidi","Aldo Baglio, Giovanni Storti, Giacomo Poretti,...",Massimo Venier,"Comedy Aldo Baglio, Giovanni Storti, Giacomo ..."
4257,310126,"Il ricco, il povero e il maggiordomo",tt4229938,NaN,Comedy,NaN,NaN,"Aldo Baglio, Giovanni Storti, Giacomo Poretti,...",Aldo Baglio,"Comedy Aldo Baglio, Giovanni Storti, Giacomo ..."
4667,182415,"Bianca come il latte, rossa come il sangue",tt2447934,NaN,"Drama, Comedy",NaN,Lux Vide,"Filippo Scicchitano, Aurora Ruffino, Luca Arge...",Giacomo Campiotti,"Drama, Comedy Filippo Scicchitano, Aurora Ruf..."

In [26]:
df[df['genres'].isna()]

,id,title,imdb_id,overview,genres,tagline,production_companies,cast,director,tags
2402,1777,Fahrenheit 9/11,tt0361596,Michael Moore's view on what happened to the U...,NaN,Controversy... what controversy?,"BIM Distribuzione, Fellowship Adventure Group","Robert De Niro, Michael Moore, George W. Bush,...",Michael Moore,Michael Moore's view on what happened to the U...

In [27]:
df[df['cast'].isna()]

,id,title,imdb_id,overview,genres,tagline,production_companies,cast,director,tags
2096,399106,Piper,tt5613056,A mother bird tries to teach her little one ho...,"Family, Animation",NaN,"Pixar Animation Studios, Disney",NaN,Alan Barillaro,A mother bird tries to teach her little one ho...
3581,13060,Lifted,tt0945571,When an overconfident teen alien gets behind t...,Animation,Failure is an option.,Pixar Animation Studios,NaN,Gary Rydstrom,When an overconfident teen alien gets behind t...
4331,13016,Zeitgeist,tt1166827,Zeitgeist: the Movie is a 2007 documentary fil...,"Documentary, History",NaN,Gentle Machine Productions LLC,NaN,Peter Joseph,Zeitgeist: the Movie is a 2007 documentary fil...
4622,14002,Baraka,tt0103767,This is a paralyzingly beautiful documentary w...,Documentary,A world beyond words.,Magidson Films,NaN,Ron Fricke,This is a paralyzingly beautiful documentary w...
4762,13925,Luxo Jr.,tt0091455,A baby lamp finds a ball to play with and it's...,Animation,NaN,Pixar Animation Studios,NaN,John Lasseter,A baby lamp finds a ball to play with and it's...
4816,455661,In a Heartbeat,tt6969946,A closeted boy runs the risk of being outed by...,"Family, Animation, Romance, Comedy",The Heart Wants What The Heart Wants,Ringling College of Art and Design,NaN,Beth David,A closeted boy runs the risk of being outed by...

In [28]:
df[df.duplicated()].shape

(0, 10)

In [29]:
df.shape

(4995, 10)

In [44]:
'''import pickle
pickle.dump(df, open('movies.pkl', 'wb'))'''

### Text Pre-Processing and Vectorization

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
# Text Processing done in tfidf vectorizer itself
# max_features=50000 --> keeps only the 50000 most used tokens
# stop_words='english' --> removes all stop words from corpus
# lowercase=True --> converts all text to lowercase
# ngram_range=(1,2) --> utilizes bi-grams. Two words together rather than singular words
# token_pattern=r'(?u)\b[a-zA-Z]{2,}\b' --> Removes punctuation automatically, Keeps words with length ≥ 2, Removes most special characters implicitly
# min_df=3 --> removes words/tokens that do not occur in >=3 records
tfidf = TfidfVectorizer(
    max_features=50000,
    stop_words='english',
    lowercase=True,
    ngram_range=(1,2),
    token_pattern=r'(?u)\b[a-zA-Z]{2,}\b',
    min_df=3
)

vectors = tfidf.fit_transform(df['tags'])

### Recommendation Model

In [31]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [ ]:
'''pickle.dump(similarity, open('similarity.pkl', 'wb'))'''

In [32]:
similarity[0][1]  # similarity between movie 0 and movie 1

np.float64(0.07569324618341262)

In [33]:
def recommend(movie_title):
    if movie_title not in df['title'].values:
        return "Movie not found"
    
    idx = df[df['title'] == movie_title].index[0] #Returns index value of the movie entered in
    
    sim_scores = cosine_similarity(vectors[idx].reshape(1, -1), vectors)[0] # Finds similarity score of all values in our vectors wrt movie_title index
    
    sim_scores = list(enumerate(sim_scores)) # store similarity scores along with index
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:11] # Store only the top 10 movies with lowest similarity score/distance. Exclude the first as this will coincide with the movie_title itself
    
    movie_indices = [i[0] for i in sim_scores] # return the index values of sim_scores
    
    return df['title'].iloc[movie_indices] # Filter titles from dataframe

### Testing Recoomendation on a sample of Movies

In [34]:
recommend("Rocky")

1251       Rocky III
1571         Rocky V
1185        Rocky II
1139        Rocky IV
530            Creed
1305    Rocky Balboa
735      The Fighter
3867          Batman
4911      Undisputed
2829    Over the Top
Name: title, dtype: object

In [35]:
recommend('The Lord of the Rings: The Fellowship of the Ring')

26              The Lord of the Rings: The Two Towers
20      The Lord of the Rings: The Return of the King
18                  The Hobbit: An Unexpected Journey
129               The Hobbit: The Desolation of Smaug
4154                            The Lord of the Rings
107         The Hobbit: The Battle of the Five Armies
90         Pirates of the Caribbean: Dead Man's Chest
1161                                      Raging Bull
130          Pirates of the Caribbean: At World's End
317                                              Troy
Name: title, dtype: object

In [36]:
recommend('Logan')

214                             X2
172       X-Men Origins: Wolverine
164                          X-Men
171                  The Wolverine
54      X-Men: Days of Future Past
211          X-Men: The Last Stand
332                     Real Steel
4963                    Sin Nombre
2295                Kate & Leopold
2259                        Morgan
Name: title, dtype: object

In [37]:
recommend('Jurassic Park')

371          The Lost World: Jurassic Park
16                          Jurassic World
478                      Jurassic Park III
2299                            Free Willy
997     Close Encounters of the Third Kind
4092                            Austenland
1638                  The Land Before Time
696                                   Hook
4256                             Dead Calm
4740         Tremors 3: Back to Perfection
Name: title, dtype: object

In [38]:
recommend('Spider-Man')

205                   Spider-Man 3
150                   Spider-Man 2
212     Oz: The Great and Powerful
4748         Shadow of the Vampire
2178                  Bachelorette
1855       xXx: State of the Union
156       The Amazing Spider-Man 2
762                 The Great Wall
1544              Midnight Special
3824                     Red Sonja
Name: title, dtype: object

In [39]:
recommend('The Matrix')

265     The Matrix Revolutions
219        The Matrix Reloaded
2274             The Animatrix
3259                Red Planet
3067            Man of Tai Chi
307       John Wick: Chapter 2
2149                The Colony
4535             The Bad Batch
867                    Pompeii
4663                     Pulse
Name: title, dtype: object